export { default as IArguments } from './Arguments.interface'
export { default as IColumn    } from './Column.interface'
export { default as INode      } from './Node.interface'
export { default as ITable     } from './Table.interface'
export { default as ITitle     } from './Title.interface'